# This is a basic workflow to help you get started with Actions
name: build CI docker image

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'ci/**'
      - '.github/workflows/build-docker-ci.yml'
  push:
    branches: [ main ]
    paths:
      - 'ci/**'
      - '.github/workflows/build-docker-ci.yml'

jobs:

  build-and-publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: cedricpinson/shaderjoy/shaderjoy-ci
          tag_with_sha: true
          path: ci/
          push: ${{ github.event_name != 'pull_request' }}

